### PR TITLE
Update gate pipeline status requirement

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Zuul version 3.0.2 changed the requirements to regexp. This change fixes
the gate status require

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck (container was missing pycodestyle)

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
Please wait before we update the zuul service before approving this change.

**Comment by TristanCacqueray** [comment]
recheck

**Review by gundalow — APPROVED** [review]

**Pull request merged**
