### PR TITLE
Set the default branch for ansible to devel

### PR DESCRIPTION
**Pull request by jeblair**

### CODE REVIEW

**Comment by gundalow** [comment]
I need to think on this one.
implicit vs explicit

**Comment by jeblair** [comment]
I'd recommend merging this regardless -- you can still choose to explicitly check out certain branches in jobs, but this will let Zuul do the right thing by default with its branch selection algorithm.

I look at it as just giving Zuul complete information about the project -- because right now, the default branch is "master" which is not correct for Ansible.

**Comment by gundalow** [comment]
recheck

**Review by gundalow — APPROVED** [review]

**Comment by gundalow** [comment]
Ah, that explains why I once saw an error message about `master` when I'd broken some other configuration. Thanks, will merge

**Pull request merged**
